<?php

use Magebit\Faq\Block\QuestionList;

/** @var QuestionList $block */
?>

<div>
    <div id="accordion">
    <?php
    $faqArray = $block->getFaqList();

    foreach ($faqArray as $qa) {
        echo "<div data-role='collapsible' class='accordion-question'>
                <div data-role='trigger'>
                    <span>" . $qa['question'] . "</span>
                </div>
            </div>
            <div data-role='content' class='accordion-answer'>" . $qa['answer'] . "</div>";
    }
    ?>
    </div>
</div>

<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#accordion").accordion();
    });
</script>
