<?php

use Magebit\PageListWidget\Block\Widget\PageList;

/** @var PageList $block */
?>
<!--Selected pages display block-->
<div>
    <h3><?= $block->getTitle() ?></h3>
    <ul>
        <?php
        $pagesHtml = "";
        $pagesArray = $block->getSelectedPages();

        foreach ($pagesArray as $url => $title) {
            $pagesHtml .= "<li><a href='" . $url . "'>" . $title . "</a></li>";
        }

        echo $pagesHtml;
        ?>
    </ul>
</div>


