<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <button class="product-qty-decr" type="button" onclick="this.nextElementSibling.value -= 1">-</button>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <button class="product-qty-incr" type="button" onclick="this.previousElementSibling.value -= -1">+</button>
                        <?php
                        $productAvail = $block->getProduct()->getQuantityAndStockStatus();
                        if ($productAvail["is_in_stock"] == 1) {
                            $imageSrc = "src='" . $block->getViewFileUrl('Magento_Catalog::images/instock.svg') . "'";
                            echo "<p class='product-stock-status'><img ". $imageSrc . "id='product-instock-image' width='11px' height='8px'/><b>IN STOCK</b>" . " " . $productAvail["qty"] . " items available</p>";
                        } else {
                            echo "<p class='product-stock-status'><b>OUT OF STOCK</b></p>";
                        }
                        ?>

                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
